# Generated by Django 2.1.7 on 2019-04-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proiect_licenta', '0003_auto_20190417_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_title',
            field=models.ImageField(default='static/images/pamant.jpg', upload_to='C:\\Users\\Ghindea Gabriel\\Documents\\New folder\\facultate\\licenta\\media'),
        ),
    ]
