# Generated by Django 2.1.7 on 2019-04-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proiect_licenta', '0005_auto_20190418_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_title',
            field=models.ImageField(default='static/images/pamant.jpg', upload_to=''),
        ),
    ]
