# Generated by Django 2.1.7 on 2019-04-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proiect_licenta', '0012_auto_20190424_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_title',
            field=models.ImageField(default='proiect_licenta/static/images/pamant.jpg', upload_to=''),
        ),
    ]
