# Generated by Django 2.1.7 on 2019-04-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proiect_licenta', '0013_auto_20190424_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_title',
            field=models.ImageField(default='/static/images/pamant.jpg', upload_to=''),
        ),
    ]
