# Generated by Django 2.1.7 on 2019-04-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proiect_licenta', '0015_auto_20190424_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_title',
            field=models.ImageField(default='/static/images/pamant.jpg', upload_to=''),
        ),
    ]
