# Generated by Django 2.1.7 on 2019-04-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proiect_licenta', '0017_auto_20190424_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_title',
            field=models.ImageField(default='/proiect_licenta/static/images/pamant.jpg', upload_to=''),
        ),
    ]
