# Generated by Django 2.1.7 on 2019-04-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proiect_licenta', '0018_auto_20190424_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_title',
            field=models.ImageField(default='pamant.jpg', upload_to=''),
        ),
    ]
