# Generated by Django 2.1.7 on 2019-04-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proiect_licenta', '0019_auto_20190425_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_title',
            field=models.ImageField(default='man.jpg', upload_to=''),
        ),
    ]
