# Generated by Django 2.1.7 on 2019-04-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proiect_licenta', '0020_auto_20190425_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_title',
            field=models.ImageField(default='/media/images/man.jpg', upload_to=''),
        ),
    ]
