# Generated by Django 2.1.7 on 2019-04-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proiect_licenta', '0023_auto_20190426_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.CharField(choices=[('cele_mai_noi_stiri', 'Cele mai noi stiri'), ('fotbal', 'Fotbal'), ('tenis', 'Tenis'), ('stiri_externe', 'Stiri externe'), ('handbal', 'Handbal')], default='Fotbal', max_length=200),
        ),
    ]
