# Generated by Django 2.1.7 on 2019-05-27 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proiect_licenta', '0028_userprofileinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
    ]
