# Generated by Django 2.1.7 on 2019-06-10 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proiect_licenta', '0034_auto_20190610_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
